sudo: required
services:
  - docker

before_install:
  - docker build -t jaworek/multi-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jaworek/multi-client-test npm run test -- --coverage

after_success:
  - docker build -t jaworek/multi-client ./client
  - docker build -t jaworek/multi-nginx ./nginx
  - docker build -t jaworek/multi-server ./server
  - docker build -t jaworek/multi-worker ./worker
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  - docker push jaworek/multi-client
  - docker push jaworek/multi-nginx
  - docker push jaworek/multi-server
  - docker push jaworek/multi-worker

#deploy:
#  provider: elasticbeanstalk
#  region: "eu-central-1"
#  app: "frontend"
#  env: "Frontend-env"
#  bucket_name: "elasticbeanstalk-eu-central-1-016182127253"
#  bucket_path: "frontend"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"